artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source: cfilt/iitb-english-hindi 
  local_data_file: artifacts/data_ingestion/train.csv


data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["test.csv", "train.csv", "validation.csv"]

data_transformation:
  root_dir: artifacts/data_transformation
  tokenizer_name: Helsinki-NLP/opus-mt-en-hi
  source: cfilt/iitb-english-hindi