artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source: cfilt/iitb-english-hindi 


data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["test", "train", "validation"]

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion
  tokenizer_name: Helsinki-NLP/opus-mt-en-hi
  source: cfilt/iitb-english-hindi

model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation
  model_ckpt: Helsinki-NLP/opus-mt-en-hi

model_predictor:
  data_path: artifacts/data_transformation
  model_ckpt: Helsinki-NLP/opus-mt-en-hi
  model_path: artifacts/model_trainer/