artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source: samsum # used for testing purposes 
  local_data_file: artifacts/data_ingestion/train.csv


data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["test.csv", "train.csv", "validation.csv"]
 